# Generated by Django 2.2 on 2020-02-11 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
