# Generated by Django 2.2 on 2020-02-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_recentwork_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='short_description',
        ),
    ]
