# Generated by Django 2.2 on 2020-02-13 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_remove_about_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
